cdir=pwd;
addpath([cdir '/utils']);

dir_save = 'results/mnl1l2time/';
if ~exist(dir_save)
  mkdir(dir_save)
end
label_fmt = 'Subject=%s_lambda=%g_time_scalest.mat';

subjects = {'A','B'}

Tab = cell2mat({'A','B','C','D','E','F';...
       'G','H','I','J','K','L';...
       'M','N','O','P','Q','R';...
       'S','T','U','V','W','X';...
       'Y','Z','1','2','3','4';...
       '5','6','7','8','9','_'});


clsopt = struct('W0',[],'nSamples', 37, 'nChannels', 64, 'ncls', 6, ...
                'solver','mnl1l2', 'whitening', 'scalest', 'group','time','display', 2);
 
classy = {'mnl1l2', [], clsopt};
lambda = exp(linspace(log(100),log(0.01),20));
model  = struct('classifier', {classy},...
              'decoder', {{'p300_decode', Tab}});

[result,acccum]=p300_xval(subjects,...
                          lambda,...
                          model,...
                          dir_save,...
                          'label_fmt', label_fmt);


lmdmark = [8.86 14.4];
[D,memo]=plot_result_p300(dir_save, label_fmt,...
                 'showspec',1,'normx',1,'reg','gl','group','time','ylim',[40 100],'mark_lambda',lmdmark);

