cdir=pwd;
addpath([cdir '/utils']);

pow = -0.25;
dir_save = 'results/mnds/';
label_fmt = sprintf('Subject=%%s_C=%%g_exp=%g',pow);

subjects = {'A','B'}

Tab = cell2mat({'A','B','C','D','E','F';...
       'G','H','I','J','K','L';...
       'M','N','O','P','Q','R';...
       'S','T','U','V','W','X';...
       'Y','Z','1','2','3','4';...
       '5','6','7','8','9','_'});


clsopt = struct('W0',[],'nSamples', 37, 'nChannels', 64, 'ncls', 6, ...
                'solver','projgrad', 'whitening', {{'st',pow,pow}}, 'display', 2);
 
classy = {'mnds', [], clsopt};
lambda = exp(linspace(log(10),log(0.1),20));
model  = struct('classifier', {classy},...
              'decoder', {{'p300_decode', Tab}});

[result,acccum]=p300_xval(subjects,...
                          lambda,...
                          model,...
                          dir_save,...
                          'label_fmt', label_fmt);


lmdmark=[1.4385 1.1288];
[D,memo]=plot_result_p300(dir_save, label_fmt,...
'showspec',1,'lambda',lambda,'ylim',[40, 100],'normx',1,'mark_lambda',lmdmark);