

model_opt = struct('nSamples', 50,...
                   'nChannels', 28,...
                   'whitening', {{'st',-0.2500,-0.2500}},...
                   'solver',  'dal',...
                   'reg', 'ds',...
                   'loss', 'lr',...
                   'epsg', 0,...
                   'epsf', 1e-3,...
                   'W0', [],...
                   'display',2);

model = {'ds_1st2nd', [], model_opt};


% 1st2nd
dir_result = 'results/bcicomp2003iv/lrds_1st2nd/';
opt=struct('band1', 20, 'band2', {{[7 30]}},...
           'file_suf','_1st2nd_ds','xTrials', [2 10]);
lambda=exp(linspace(log(10), log(0.001), 20));
[memo,opt] = xval_bcicomp2003iv_mb(lambda, model, dir_result, opt);

%% 1stalpbet
dir_result = 'results/bcicomp2003iv/lrds_1stalpbet/';
opt=struct('band1', 20, 'band2', {{[7 15],[15 30]}},...
           'file_suf','_1stalpbet_ds','xTrials', [2 10]);
lambda=exp(linspace(log(10), log(0.001), 20));
[memo,opt] = xval_bcicomp2003iv_mb(lambda, model, dir_result, opt);

nm=cell2mat(getfieldarray(memo,'nm'))
acc=cell2mat(getfieldarray(memo,'acc'))
loss=cell2mat(getfieldarray(memo,'loss'))
loss_std=cell2mat(getfieldarray(memo,'loss_std'));
figure, [h,acc,D,I]=plot_bcicomp2003iv(lambda, memo, 'normx',1,'v', ...
                                       memo(1).C.v,'reg','ds');

